### ISSUE TITLE
Error when installing on windows 10x64

### ISSUE THREAD

**Issue by satishkrr** [ovalhub/pyicu#126]
(base) C:\Users\satis\anaconda3\polyglot>pip install PyICU==2.4.3
Collecting PyICU==2.4.3
  Using cached PyICU-2.4.3.tar.gz (219 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\satis\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\satis\\AppData\\Local\\Temp\\pip-install-2r5mujdm\\PyICU\\setup.py'"'"'; __file__='"'"'C:\\Users\\satis\\AppData\\Local\\Temp\\pip-install-2r5mujdm\\PyICU\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\pip-egg-info'
         cwd: C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\
    Complete output (53 lines):
    (running 'icu-config --version')
    (running 'pkg-config --modversion icu-i18n')
    Traceback (most recent call last):
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 62, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "C:\Users\satis\anaconda3\lib\os.py", line 679, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 65, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 18, in check_output
        return subprocess_check_output(popenargs)
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 68, in <module>
        ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 18, in check_output
        return subprocess_check_output(popenargs)
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\satis\anaconda3\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\satis\AppData\Local\Temp\pip-install-2r5mujdm\PyICU\setup.py", line 73, in <module>
        ''')
    RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ovalhub** [comment]
You need to install ICU first. Then, you need to tell PyICU where to find the ICU header files and libraries by editing PyICU's setup.py and setting the right values for the 'windows' entries in the relevant dicts or setting the corresponding env vars.
There is no auto-installing via pkg-config on Windows, maybe with icu-config if it is still available with the version of ICU you installed. Just edit setup.py as required.

Andi..
