### ISSUE TITLE
test failure in TestDateTimePatternGenerator

### ISSUE THREAD

**Issue by lfam** [ovalhub/pyicu#28]
I am trying to build PyICU 1.9.3 (plus the fix for #19 ) using GNU Guix. I get the following test failure.

```
======================================================================
FAIL: testAddPattern (test.test_DateTimeParserGenerator.TestDateTimePatternGenerator)
Test overwriting a pattern with the same skeleton.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-pyicu-1.9.3.drv-0/PyICU-1.9.3/test/test_DateTimeParserGenerator.py", line 47, in testAddPattern
    self.assertEqual(sdf.format(self.date), '09 mai à 17:30')
AssertionError: '09 mai 17:30' != '09 mai à 17:30'
- 09 mai 17:30
+ 09 mai à 17:30
?       ++


----------------------------------------------------------------------
Ran 37 tests in 0.637s

FAILED (failures=1)
```

I'm using python-3.4.3, icu4c-55.1, perl-5.22.1. Let me know what other information could help debug this.

**Comment by ovalhub** [comment]
On Thu, 18 Aug 2016, lfam wrote:

> I am trying to build PyICU 1.9.3 (plus the fix for #19 ) using GNU Guix. I get the following test failure.
>
> ```
> ======================================================================
> FAIL: testAddPattern (test.test_DateTimeParserGenerator.TestDateTimePatternGenerator)
> Test overwriting a pattern with the same skeleton.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "/tmp/guix-build-python-pyicu-1.9.3.drv-0/PyICU-1.9.3/test/test_DateTimeParserGenerator.py", line 47, in testAddPattern
>    self.assertEqual(sdf.format(self.date), '09 mai à 17:30')
> AssertionError: '09 mai 17:30' != '09 mai à 17:30'
> - 09 mai 17:30
> + 09 mai à 17:30
> ?       ++

Are you running the latest out of trunk ?
If not, try it. I did make a fix adding some missing timezone parameter to 
prevent the global timezone from being used.

Andi..
