### ISSUE TITLE
Install fails on ubuntu 14.04 and python 2.7.6

### ISSUE THREAD

**Issue by christian-bromann** [ovalhub/pyicu#43]
When trying to pip install the package I get:

```sh
$ pip install PyICU
Collecting PyICU
  Using cached PyICU-1.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vLooPA/PyICU/setup.py", line 11, in <module>
        ICU_VERSION = subprocess.check_output(('icu-config', '--version')).strip()
      File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vLooPA/PyICU/
```

My machine data is:
```js
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

Python 2.7.6
pip 9.0.1
```

**Comment by christian-bromann** [comment]
Nevermind I had to install ICU packages via `sudo apt-get install libicu-dev`
