### ISSUE TITLE
RuntimeError: Please set the ICU_VERSION environment variable to the version of ICU you have installed.

### ISSUE THREAD

**Issue by achillesrasquinha** [ovalhub/pyicu#94]
Facing the above error during installation of PyICU. Corresponding traceback.

```
Collecting pyicu>=1.9.3 (from normality>=0.5.1->dataset->ccman==0.1.0)
  Downloading https://files.pythonhosted.org/packages/c2/15/0af20b540c828943b6ffea5677c86e908dcac108813b522adebb75c827c1/PyICU-2.2.tar.gz (211kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-sc62v7iq/pyicu/setup.py", line 43, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "/usr/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-sc62v7iq/pyicu/setup.py", line 46, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sc62v7iq/pyicu/setup.py", line 53, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.
```

**Comment by achillesrasquinha** [comment]
Solution: Make sure you've got `libicu-dev` installed (on Debian).

```
sudo apt-get install libicu-dev
```

**Comment by Infovarius** [comment]
what about Windows?

**Comment by ovalhub** [comment]
> On Aug 19, 2019, at 23:54, Anton <notifications@github.com> wrote:
> 
> what about Windows?
> 
If neither icu-config nor pkg-config are available there, you're back to the old days of editing setup.py to match your python, icu and compiler installs.
Alternatively, you can set env vars (see setup.py sources).

Andi..
